# (C) Copyright 2026 Anemoi contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

# ruff: noqa: E402

import importlib
import logging
import os

LOG = logging.getLogger(__name__)

_CLI_VERSION = os.environ.get("ANEMOI_REGISTRY_CLI_VERSION", "1")

if _CLI_VERSION not in ("1", "2"):
    raise ValueError(
        f"Invalid ANEMOI_REGISTRY_CLI_VERSION={_CLI_VERSION!r}. "
        "Supported values: '1' (legacy, default), '2' (new)."
    )

_active = importlib.import_module(f".v{_CLI_VERSION}", __name__)

config = _active.config

CatalogueEntryNotFound = _active.CatalogueEntryNotFound
Dataset = _active.Dataset
DatasetsList = _active.DatasetsList
Experiment = _active.Experiment
ExperimentsList = _active.ExperimentsList
Weights = _active.Weights
WeightsList = _active.WeightsList
Task = _active.Task
TasksList = _active.TasksList

# v2-only entry types (Site, Replica)
if _CLI_VERSION == "2":
    Site = _active.Site
    SitesList = _active.SitesList
    Replica = _active.Replica
    ReplicasList = _active.ReplicasList


def publish_dataset(*args, **kwargs):
    return Dataset.publish(*args, **kwargs)


try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__  # type: ignore
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


__all__ = [
    "CatalogueEntryNotFound",
    "Dataset",
    "DatasetsList",
    "Experiment",
    "ExperimentsList",
    "Task",
    "TasksList",
    "Weights",
    "WeightsList",
    "config",
]

if _CLI_VERSION == "2":
    __all__ += [
        "Replica",
        "ReplicasList",
        "Site",
        "SitesList",
    ]
