registry:
  # can be overridden either by
  # - an entry in the anemoi config file (~/.config/anemoi/settings.toml)
  # [registry]
  # settings=...
  # - or with the environment variable ANEMOI_CONFIG_REGISTRY_SETTINGS=...
  settings: "https://anemoi.ecmwf.int/settings"

  workers:
    # These are the default values for the workers
    # the are experimental and can change in the future
    heartbeat: 60
    max_no_heartbeat: -1
    wait: 10
    transfer-dataset:
      target_dir: "."
      published_target_dir: null
      threads: 1
      auto_register: true
    dummy:
      arg: default_value
