registry:
  api_url: "https://anemoi.ecmwf.int/api/v1"

  plots_uri_pattern: "s3://ml-artefacts/{expver}/{basename}"
  datasets_uri_pattern: "s3://ml-datasets/{name}"
  weights_uri_pattern: "s3://ml-weights/{uuid}.ckpt"
  weights_platform: "ewc"
