# (C) Copyright 2024 Anemoi contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

# ruff: noqa: E402

import importlib
import logging
import os

from anemoi.utils.config import DotDict
from anemoi.utils.config import load_any_dict_format
from anemoi.utils.config import load_config

from anemoi.registry.rest import Rest

LOG = logging.getLogger(__name__)


# TODO : move this function to anemoi.utils.config
def package_config(module_name, missing_ok=False):
    """Load the config.yaml file from the package directory, if it exists."""
    module = importlib.import_module(module_name)
    path = os.path.join(os.path.dirname(module.__file__), "config.yaml")
    if not os.path.exists(path):
        if missing_ok:
            return {}
        else:
            raise FileNotFoundError(f"Config file not found: {path}")

    return load_any_dict_format(path)


class SingletonConfig:
    def __init__(self):
        self._cache = None
        self.package_config = package_config("anemoi.registry")

        url = self.package_config["registry"]["settings"]
        if os.environ.get("ANEMOI_TESTING") and not os.environ.get("ANEMOI_TESTING") == "0":
            url = self.package_config["registry"]["test-settings"]
            LOG.warning("Using default settings URL for testing: %s", url)
        self.default_url = url

    def _settings_url_and_token(self):
        # overwritten by config from user
        config = load_config(secrets=["api_token"]).get("registry")
        url = config["settings"] or self.default_url
        if url != self.default_url:
            LOG.warning(f"Overriding default settings URL {self.default_url} with {url} from user config.")

        if url == "-":
            return None, None

        # use the token to retrieve the settings from the server
        if "api_token" not in config:
            raise ValueError("Missing api_token in config")
        token = config["api_token"]

        return url, token

    def _config_from_server(self):

        url, token = self._settings_url_and_token()
        if not url:
            return {}

        return Rest(token=token).get_url(url)

    def __call__(self, with_secrets=True):
        if self._cache:
            return self._cache

        # from this anemoi-registry package
        conf = self.package_config["registry"]
        conf = DotDict(conf)

        # overwritten by server config
        for k, v in self._config_from_server()["registry"].items():
            if k not in conf:
                conf[k] = v
            elif isinstance(conf[k], dict) and isinstance(v, dict):
                conf[k].update(v)

        # partly overwritten by config from user
        user_config = load_config(secrets=["api_token"])["registry"]
        for k, v in user_config.items():
            if k in ["api_token"]:  # use token
                conf[k] = v
                continue
            if k in ["allow_delete", "allow_edit_entries"]:  # use these flags, to be removed
                conf[k] = v
                LOG.warning(
                    f"Overriding default {k} with {v} from user config, these flags will disapppear in the future."
                )
                continue
            if v != conf.get(k):  # ignore other keys
                LOG.warning(
                    (
                        f"Ignoring user config for {k}: {v} != {conf.get(k)}."
                        "Please delete this entry from your config file."
                    )
                )
        conf.pop("settings")
        conf.pop("test-settings")
        self._cache = conf

        if not with_secrets:
            conf = DotDict({k: v if k != "api_token" else "***" for k, v in conf.items()})
        return conf


CONF = SingletonConfig()


def publish_dataset(*args, **kwargs):
    return Dataset.publish(*args, **kwargs)


from .entry.dataset import DatasetCatalogueEntry as Dataset
from .entry.dataset import DatasetCatalogueEntryList as DatasetsList
from .entry.experiment import ExperimentCatalogueEntry as Experiment
from .entry.experiment import ExperimentCatalogueEntryList as ExperimentsList
from .entry.weights import WeightCatalogueEntry as Weights
from .entry.weights import WeightsCatalogueEntryList as WeightsList
from .tasks import TaskCatalogueEntry as Task
from .tasks import TaskCatalogueEntryList as TasksList

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__  # type: ignore
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


__all__ = [
    "Weights",
    "WeightsList",
    "Experiment",
    "ExperimentsList",
    "Dataset",
    "DatasetsList",
    "Task",
    "TasksList",
]
